# Basic `dependabot.yml` file with
# minimum configuration for two package managers

version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: develop
    schedule:
      interval: monthly

  - package-ecosystem: 'docker'
    directory: '/'
    target-branch: develop
    schedule:
      interval: monthly
