name: ci

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
        env:
          NODE_END: test

      - name: Run Linter
        run: npm run lint:fix

      - name: Run Formatter
        run: npm run format
